apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - viewer
  - proxy

configMapGenerator:
  - name: config
    literals:
      - HOST_NAME=

vars:
  - name: HOST_NAME
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: config
    fieldref:
      fieldpath: data.HOST_NAME