apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 52north2

bases:
  - ../base

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - HOST_NAME=v2.ppe.data.europa.eu

images:
  - name: 52north/deu-viewer:0.9.9
  - name: 52north/deu-proxy:latest
    newTag: ppe2