apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 52north

resources:
  - ../base

configMapGenerator:
  - name: config
    behavior: merge
    literals:
      - HOST_NAME=ppe.data.europa.eu
      - API_HOST_NAME=ppe.data.europa.eu

images:
  - name: 52north/deu-geoviewer:latest
    newTag: 1.0.6
  - name: 52north/deu-geoviewer-proxy:latest
    newTag: 2.0.3